{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Test_File_003.Test_Credence_003 object at 0x0000025F386D2C50>\n\n>   ???\nE   assert False\n\nD:\\PYTHON DATA OF PRACTICE\\Python Pytest Framework\\Test_File_003.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "d62b3572-856e-4ae2-89a6-7f5b0d496850-attachment.txt", "type": "text/plain"}], "start": 1690711670532, "stop": 1690711670532, "uuid": "f061c96a-d07a-4334-a1c2-51ef055937bd", "historyId": "2ecc1bd0ad306d505ac1278164cdeef4", "testCaseId": "2ecc1bd0ad306d505ac1278164cdeef4", "fullName": "Python-Pytest-Framework.Test_File_003.Test_Credence_003#test_mul_004", "labels": [{"name": "parentSuite", "value": "Python-Pytest-Framework"}, {"name": "suite", "value": "Test_File_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DARKKING"}, {"name": "thread", "value": "18080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Python-Pytest-Framework.Test_File_003"}]}